# Generated by Django 5.2.6 on 2025-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
