# Generated by Django 4.0.4 on 2025-09-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_book_quantity_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Books/'),
        ),
    ]
